### ISSUE TITLE
Looking for RapidJSON, crossguid and JsonSchemaBuilder should be done after the repository is cloned

### ISSUE THREAD

**Issue by oyviaase** [kekePower/build.leia#2]
The installation process crashes if the installer does not find RapidJSON, crossguid or JsonSchemaBuilder, and that the source code for Kodi is not downloaded. Since the installer tries to change directories to a non existing directory.

**Comment by kekePower** [comment]
Hi.

Thanks for your report. I'll look into it.

Cheers,
kekePower

**Comment by kekePower** [comment]
@oyviaase Thanks again for your report. It is fixed in 8d5af6a.

Cheers,
kekePower
